import 'package:adminforhamropalika/model/complaint_model.dart';
import 'package:adminforhamropalika/services/complaint_db_services.dart';
import 'package:flutter/material.dart';



class ComplaintViewModel extends ChangeNotifier {
  ComplaintViewModel() {
    getAllComplaint();
  }

  List<Complaint> _complains = [];
  List<Complaint> get complains => _complains;

  ComplaintDb cp = ComplaintDb();

  Future<String> addComplaint(Complaint complains) async {
    String autoGeneratedId = await cp.addComplaint(complains);
    getAllComplaint();
    notifyListeners();
    return autoGeneratedId;
  }

  getAllComplaint() async {
    _complains = await cp.getAllComplaint();
    notifyListeners();
  }
}
