

import 'package:adminforhamropalika/model/newsfeed_model.dart';
import 'package:adminforhamropalika/services/newsfeed_db_services.dart';
import 'package:flutter/material.dart';








class NewsFeedViewModel extends ChangeNotifier {
  NewsFeedViewModel() {
  getAllNewsFeed();
  }

  List<NewsFeed> _newsfeeds = [];
  List<NewsFeed> get newsfeed => _newsfeeds;

  NewsFeedDb db = NewsFeedDb();

  Future<String> addpost(NewsFeed newsFeed) async {
    String autoGeneratedId = await db.addpost(newsFeed);
   getAllNewsFeed();
    notifyListeners();
    return autoGeneratedId;
  }

 getAllNewsFeed() async {
    _newsfeeds = await db.getAllNewsFeed();
    notifyListeners();
  }
}
