
import 'package:adminforhamropalika/model/notice_model.dart';
import 'package:adminforhamropalika/services/notice_db_services.dart';
import 'package:flutter/material.dart';





class UsernoticeViewModel extends ChangeNotifier {
  UsernoticeViewModel() {
  getAllusernotice();
  }

  List<UserNotice> _userNotices = [];
  List<UserNotice> get userNotices => _userNotices;

  UsernoticeDb db = UsernoticeDb();

  Future<String> addnotice(UserNotice notices) async {
    String autoGeneratedId = await db.addnotice(notices);
   getAllusernotice();
    notifyListeners();
    return autoGeneratedId;
  }

 getAllusernotice() async {
    _userNotices = await db.getAllusernotice();
    notifyListeners();
  }
}
